/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "写给小猪头(LOVING)",
  "description": "情不知所起却一往情深！",
  "base": "/liangshuangshuang/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/liangshuangshuang/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "lang": "en-US",
        "heroImage": "/favicon.png",
        "bannerBg": "/favicon.png",
        "heroText": "微服务",
        "tagline": "公众号前端微服务",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "navbar": false,
        "sidebar": false,
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。",
            "link": "/guide/",
            "imgUrl": "/favicon.ico"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。",
            "link": "/guide/",
            "imgUrl": "/favicon.ico"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。",
            "link": "/guide/",
            "imgUrl": "/favicon.ico"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-e557697c",
      "path": "/",
      "lastUpdated": "6/24/2020, 4:50:31 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-7cbb5e41",
      "path": "/config.html",
      "lastUpdated": "4/9/2020, 8:29:39 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-40416856",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Welcome to GitHub Pages",
          "slug": "welcome-to-github-pages"
        },
        {
          "level": 3,
          "title": "Markdown",
          "slug": "markdown"
        },
        {
          "level": 3,
          "title": "Jekyll Themes",
          "slug": "jekyll-themes"
        },
        {
          "level": 3,
          "title": "Support or Contact",
          "slug": "support-or-contact"
        }
      ],
      "lastUpdated": "6/23/2020, 6:25:20 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/pages/",
      "relativePath": "pages/README.md",
      "key": "v-6b41a445",
      "path": "/pages/",
      "headers": [
        {
          "level": 2,
          "title": "Welcome to GitHub Pages",
          "slug": "welcome-to-github-pages"
        },
        {
          "level": 3,
          "title": "Markdown",
          "slug": "markdown"
        },
        {
          "level": 3,
          "title": "Jekyll Themes",
          "slug": "jekyll-themes"
        },
        {
          "level": 3,
          "title": "Support or Contact",
          "slug": "support-or-contact"
        }
      ],
      "lastUpdated": "6/26/2020, 4:31:51 PM"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "lang": "en-US",
        "heroImage": "/favicon.png",
        "bannerBg": "/favicon.png",
        "heroText": "微服务",
        "tagline": "公众号前端微服务",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "navbar": true,
        "sidebar": false,
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。",
            "link": "/guide/",
            "imgUrl": "/favicon.png"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。",
            "link": "/guide/",
            "imgUrl": "/favicon.png"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。",
            "link": "/guide/",
            "imgUrl": "/favicon.png"
          }
        ]
      },
      "regularPath": "/zh/",
      "relativePath": "zh/README.md",
      "key": "v-d5180e36",
      "path": "/zh/"
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/config.html",
      "relativePath": "zh/config.md",
      "key": "v-6d81e566",
      "path": "/zh/config.html",
      "lastUpdated": "6/26/2020, 4:31:51 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/guide/",
      "relativePath": "zh/guide/README.md",
      "key": "v-6ec597f8",
      "path": "/zh/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Welcome to GitHub Pages",
          "slug": "welcome-to-github-pages"
        },
        {
          "level": 3,
          "title": "Markdown",
          "slug": "markdown"
        },
        {
          "level": 3,
          "title": "Jekyll Themes",
          "slug": "jekyll-themes"
        },
        {
          "level": 3,
          "title": "Support or Contact",
          "slug": "support-or-contact"
        }
      ],
      "lastUpdated": "6/26/2020, 4:31:51 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/zh/pages/",
      "relativePath": "zh/pages/README.md",
      "key": "v-1519fcf8",
      "path": "/zh/pages/",
      "headers": [
        {
          "level": 2,
          "title": "Welcome to GitHub Pages",
          "slug": "welcome-to-github-pages"
        },
        {
          "level": 3,
          "title": "Markdown",
          "slug": "markdown"
        },
        {
          "level": 3,
          "title": "Jekyll Themes",
          "slug": "jekyll-themes"
        },
        {
          "level": 3,
          "title": "Support or Contact",
          "slug": "support-or-contact"
        }
      ],
      "lastUpdated": "6/26/2020, 4:31:51 PM"
    }
  ],
  "themeConfig": {
    "logo": "/favicon.ico",
    "repo": "vuejs/vuepress",
    "nav": [
      {
        "text": "首页",
        "ariLabel": "其他小站",
        "link": "/"
      }
    ],
    "sidebar": {
      "/standard/": [
        [
          "",
          "前言(2019)"
        ],
        {
          "title": "布局类组件",
          "collapsable": true,
          "sidebarDepth": 2,
          "children": [
            [
              "Nginx部署Vue项目",
              "Nginx部署Vue项目"
            ],
            [
              "NVM自由切换Node版本",
              "NVM自由切换Node版本小笔记"
            ],
            [
              "KTV点歌系统",
              "KTV点歌系统"
            ]
          ]
        },
        {
          "title": "可视化组件",
          "collapsable": true,
          "children": []
        },
        {
          "title": "工具类组件",
          "collapsable": true,
          "children": []
        },
        {
          "title": "方法类函数",
          "collapsable": true,
          "children": []
        }
      ]
    },
    "nextLinks": true,
    "prevLinks": true,
    "search": true,
    "sidebarDepth": 2,
    "displayAllHeaders": true,
    "searchMaxSuggestions": 10,
    "activeHeaderLinks": true,
    "lastUpdated": "最近更新",
    "repoLabel": "查看源码",
    "docsRepo": "vuejs/vuepress",
    "docsDir": "docs",
    "docsBranch": "master",
    "editLinks": true,
    "editLinkText": "帮助我们改善此页面！",
    "smoothScroll": true,
    "algolia": {
      "apiKey": "<API_KEY>",
      "indexName": "<INDEX_NAME>"
    }
  }
}